# SPDX-FileCopyrightText: 2006-2021 html5lib contributors. See AUTHORS.rst
#
# SPDX-License-Identifier: MIT

language: python
python:
  - "pypy3"
  - "pypy"
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "3.9-dev"

cache: pip

env:
  global:
    - TOXENV=base,optional,six19-optional

install:
  - pip install tox

script:
  - tox

after_script:
  - python debug-info.py
